#! /bin/bash

set -ex

# install antlr
apt-get install -y openjdk-8-jre-headless openjdk-8-jdk

wget http://www.antlr.org/download/antlr-4.7.1-complete.jar
cp antlr-4.7.1-complete.jar /usr/local/lib/
echo "export CLASSPATH=.:/usr/local/lib/antlr-4.7.1-complete.jar:$CLASSPATH" >> .bashrc
echo "alias antlr4='java -Xmx500M -cp "/usr/local/lib/antlr-4.7.1-complete.jar:$CLASSPATH" org.antlr.v4.Tool'" >> .bashrc
echo "alias grun='java org.antlr.v4.gui.TestRig'" >> .bashrc

